@startuml

class Residence {
    -bedroom: int { get set }
    -bathrooms: int { get set }
    -sqft: int { get set }
    -purchasePrice: double { get set }
    -taxes: double { get set }
    -address: String { get set } - where to put?
    -interestRate: double { get set }
    -percentageDown { get }
    -rentPerSqFoot: double { get }

    +Residence()
    +Residence(bedrooms: int, bathrooms: int, sqft: int,
         purchasePrice: double, taxes: double, address: String)

    +percentageDown(): double
    +pricePerSqFt(): double
    +monthlyPayment(): double
    +rentalIncome(): double
    +monthlyNetProfit(): double
    +toString(): String
}

class House extends Residence {

    +House()
    +House(bedrooms: int, bathrooms: int,
         sqft: int, purchasePrice: double,
         taxes: double, address: String)

    +monthlyNetProfit(): double
    +toString(): String
}

class Condo extends Residence {
    -hoaFee: double { get set }
    -amenities: String

    +Condo()
    +Condo(bedrooms: int, bathrooms: int, sqft: int,
         purchasePrice: double, taxes: double, address: String,
         hoaFee: double, amenities: String, )

    +monthlyNetProfit(): double
    +toString(): String
}

class MultiPlex extends Residence {
    -units: int { get set }
    -utilities: double { get set }

    +MultiPlex()
    +MultiPex(units: int, bedrooms: int,
         bathrooms: int, sqft: int,
         purchasePrice: double, taxes: double,
         address: String)

    +monthlyNetProfit(): double
    +toString(): String
}

realEstateInvestmentTool o-- Residence

@enduml